[build]
  base = "client"
  command = "pnpm install && pnpm run build"
  publish = "client/dist"

[context.production.environment]
  # Set this in Netlify UI to the deployed backend URL
  # VITE_API_BASE = "https://your-backend.vercel.app/api"

[dev]
  # optional: run the Netlify dev with the client
  command = "pnpm --filter ./client dev"
